version: '3'

services:
  bot:
    build: .
    container_name: telegram-bot
    volumes:
      - .:/app
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
